import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
  getBilingualValue: (value: string | { en?: string; es?: string } | null | undefined, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

// Traducciones
const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navegación y menú
    'nav.wine_catalog': 'Catálogo de Vinos',
    'nav.inventory': 'Inventario',
    'nav.analytics': 'Análisis',
    'nav.users': 'Usuarios',
    'nav.branches': 'Sucursales',
    'nav.qr_generation': 'Generar QR',
    'nav.settings': 'Configuración',
    'nav.tasting_exams': 'Exámenes de Cata',
    
    // Catálogo
    'catalog.title': 'Catálogo de Vinos',
    'catalog.search_placeholder': 'Buscar vinos...',
    'catalog.no_wines': 'No hay vinos disponibles',
    'catalog.filter_by_type': 'Filtrar por tipo',
    'catalog.filter_by_region': 'Filtrar por región',
    'catalog.all_types': 'Todos los tipos',
    'catalog.all_regions': 'Todas las regiones',
    'catalog.all': 'Todos',
    'catalog.by_glass': 'Por Copa',
    'catalog.by_bottle': 'Por Botella',
    'catalog.cocktails': 'Coctelería',
    'catalog.red': 'Tinto',
    'catalog.white': 'Blanco',
    'catalog.rose': 'Rosado',
    'catalog.sparkling': 'Espumoso',
    'catalog.dessert': 'Postre',
    'catalog.fortified': 'Fortificado',
    'catalog.edit_name': 'Editar nombre',
    'catalog.configure_name': 'Configurar nombre',
    'catalog.define_restaurant': 'Define el nombre de tu restaurante',
    'catalog.restaurant_name_placeholder': 'Nombre del restaurante',
    'catalog.sort_asc': 'A → Z',
    'catalog.loading': 'Cargando catálogo...',
    'catalog.success': 'Éxito',
    'catalog.glass_sale_enabled': 'Venta por copa habilitada.',
    'catalog.glass_sale_disabled': 'Venta por copa deshabilitada.',
    'catalog.error': 'Error',
    'catalog.error_update_config': 'No se pudo actualizar la configuración',
    'catalog.no_active_branch': 'No hay sucursal activa seleccionada',
    'catalog.invalid_price': 'Precio inválido',
    'catalog.guest_session_invalid': 'No se pudo identificar tu sesión de comensal. Vuelve a escanear el QR.',
    'catalog.out_of_stock': 'Sin stock',
    'catalog.out_of_stock_title': 'Sin Stock',
    'catalog.out_of_stock_message': 'Este vino no está disponible en este momento',
    'catalog.confirm_purchase': 'Confirmar Compra',
    'catalog.a_bottle': 'una botella',
    'catalog.a_glass': 'una copa',
    'catalog.want_to_buy': '¿Deseas comprar',
    'catalog.of_wine': 'de',
    'catalog.price_label': 'Precio',
    'catalog.cancel': 'Cancelar',
    'catalog.confirm': 'Confirmar',
    'catalog.purchase_success': '¡Compra Exitosa!',
    'catalog.purchase_success_message': 'Tu pedido ha sido registrado. El personal te lo llevará pronto.',
    'catalog.branch_unavailable': 'Sucursal no disponible',
    'catalog.branch_unavailable_message': 'No se pudo identificar la sucursal de este menú. Vuelve a escanear el QR o intenta de nuevo.',
    'catalog.owner_unknown': 'No se pudo identificar el propietario de este menú. Vuelve a escanear el QR o intenta de nuevo.',
    'catalog.purchase_error': 'No se pudo procesar la compra. Intenta de nuevo.',
    'catalog.guest_back': 'Volver',
    'catalog.guest_scan_again': 'Escanear otro QR',
    'catalog.guest_token_missing': 'Token guest faltante.',
    'catalog.guest_code_expired': 'Este código expiró o ya no es válido. Solicita uno nuevo.',
    'catalog.branch_required': 'Sin sucursal seleccionada',
    'catalog.branch_required_message': 'Selecciona una sucursal antes de editar el nombre.',
    'catalog.name_required': 'Nombre requerido',
    'catalog.name_required_message': 'Ingresa un nombre para tu restaurante o centro de consumo.',
    'catalog.saving': 'Guardando...',
    'catalog.save': 'Guardar',
    'catalog.error_update_branch_name': 'No se pudo actualizar el nombre del restaurante.',
    'catalog.pairings_no_suggested': 'Sin maridaje sugerido',
    'catalog.close': 'Cerrar',
    'catalog.session_invalid_title': 'Sesión no válida',
    'catalog.not_available': 'No disponible',
    'catalog.not_available_bottle': 'Este vino no está disponible por botella.',
    'catalog.not_available_glass': 'Este vino no está disponible por copa.',
    'catalog.branch_name_updated': 'Nombre actualizado',
    'catalog.branch_name_updated_message': 'El nombre del restaurante se actualizó correctamente.',
    
    // Vino
    'wine.name': 'Nombre',
    'wine.winery': 'Bodega',
    'wine.vintage': 'Añada',
    'wine.type': 'Tipo',
    'wine.region': 'Región',
    'wine.country': 'País',
    'wine.grape_variety': 'Variedad de Uva',
    'wine.alcohol_content': 'Grado Alcohólico',
    'wine.description': 'Descripción',
    'wine.tasting_notes': 'Notas de Cata',
    'wine.food_pairings': 'Maridajes',
    'wine.serving_temperature': 'Temperatura de Servicio',
    'wine.price_bottle': 'Precio Botella',
    'wine.price_glass': 'Precio Copa',
    'wine.stock': 'Stock',
    'wine.available_by_glass': 'Disponible por Copa',
    'wine.available_by_bottle': 'Disponible por Botella',
    'wine.bottle': 'Botella',
    'wine.glass': 'Copa',
    'wine.buy_glass': 'Comprar Copa',
    'wine.buy_bottle': 'Comprar Botella',
    'wine.recommended_pairings': 'Maridaje recomendado:',
    'wine.pairings_modal_heading_premium': 'Recomendaciones de maridaje',
    'wine.vintage_label': 'Añada:',
    'wine.config_glass_sale': 'Configurar venta por copa',
    'wine.glass_sale': 'Venta por Copa',
    'wine.enable_glass_sale': 'Habilitar la venta de este vino por copa',
    'wine.config_glass_sale_error': 'Por favor ingresa un precio válido para la copa',
    'wine.suggested_price': 'Precio sugerido',
    'wine.one_fifth_bottle': '1/5 del precio de botella',
    
    // Ficha Sensorial
    'sensory.body': 'Cuerpo',
    'sensory.sweetness': 'Dulzor',
    'sensory.acidity': 'Acidez',
    'sensory.tannin': 'Tanicidad',
    'sensory.intensity': 'Intensidad',
    'sensory.fizziness': 'Burbujeo',
    'sensory.light': 'Ligero',
    'sensory.medium': 'Medio',
    'sensory.full': 'Completo',
    'sensory.dry': 'Seco',
    'sensory.sweet': 'Dulce',
    'sensory.low': 'Baja',
    'sensory.high': 'Alta',
    'sensory.subtle': 'Sutil',
    'sensory.intense': 'Intenso',
    'sensory.still': 'Tranquilo',
    'sensory.sparkling': 'Espumoso',
    
    // Inventario
    'inventory.title': 'Gestión de Inventario',
    'inventory.low_stock': 'Stock Bajo',
    'inventory.out_of_stock': 'Sin Stock',
    'inventory.add_wine': 'Agregar Vino',
    'inventory.edit_wine': 'Editar Vino',
    'inventory.delete_wine': 'Eliminar Vino',
    'inventory.stock_quantity': 'Cantidad en Stock',
    'inventory.adjust_stock': 'Ajustar Stock',
    
    // Usuarios
    'users.title': 'Gestión de Usuarios',
    'users.pending_approval': 'Pendientes de Aprobación',
    'users.active': 'Activos',
    'users.inactive': 'Inactivos',
    'users.approve': 'Aprobar',
    'users.reject': 'Rechazar',
    'users.role': 'Rol',
    'users.status': 'Estado',
    'users.no_permissions': 'No tienes permisos para acceder a esta pantalla',
    'users.approve_user': 'Aprobar Usuario',
    'users.select_role': 'Selecciona el rol para',
    'users.approved_success': 'aprobado como',
    'users.reject_user': 'Rechazar Usuario',
    'users.reject_confirm': '¿Deseas rechazar la solicitud de',
    'users.rejected': 'Rechazado',
    'users.rejected_success': 'Solicitud de',
    'users.delete_user': 'Eliminar Usuario',
    'users.delete_confirm': '¿Estás seguro de que deseas eliminar permanentemente a',
    'users.delete_warning': 'Esta acción no se puede deshacer.',
    'users.cannot_delete_other_org': 'No puedes eliminar usuarios de otras organizaciones',
    'users.cannot_delete_same_level': 'Solo puedes eliminar usuarios con rol inferior al tuyo',
    'users.cannot_delete_other_branch': 'Solo puedes eliminar usuarios de tu sucursal',
    'users.no_delete_permission': 'No tienes permisos para eliminar usuarios',
    'users.cannot_delete_owner': 'No se puede eliminar al Owner',
    'users.change_role': 'Cambiar Rol',
    'users.select_new_role': 'Selecciona el nuevo rol para',
    'users.role_changed': 'Rol actualizado correctamente',
    'users.no_assign_permission': 'No tienes permisos para asignar roles',
    'users.approve_error': 'No se pudo aprobar el usuario',
    'users.delete_error': 'No se pudo eliminar el usuario',
    'users.deleted_success': 'ha sido eliminado correctamente.',
    'users.requesting': 'Solicita:',
    'users.branch': 'Sucursal:',
    'users.all_branches': 'Todas las sucursales',
    'users.pending_requests': 'Solicitudes Pendientes',
    'users.cannot_change_owner_role': 'No se puede cambiar el rol de un Owner',
    'users.no_modify_permission': 'No tienes permisos para modificar el rol de',
    'users.no_assign_role_permission': 'No tienes permisos para asignar el rol de',
    'users.change_role_confirm': '¿Cambiar el rol de',
    'users.change_role_from_to': 'de',
    'users.change_role_to': 'a',
    'users.role_updated': 'Rol de',
    'users.role_updated_to': 'actualizado a',
    'users.current': 'Actual',
    'users.current_role': 'Rol actual:',
    
    // Sucursales
    'branches.title': 'Gestión de Sucursales',
    'branches.subtitle': 'Administrar ubicaciones del restaurante',
    'branches.add_branch': 'Agregar Sucursal',
    'branches.create_branch': 'Crear Nueva Sucursal',
    'branches.edit_branch': 'Editar Sucursal',
    'branches.name': 'Nombre',
    'branches.address': 'Dirección',
    'branches.phone': 'Teléfono',
    'branches.email': 'Email',
    'branches.registered': 'Sucursales Registradas',
    'branches.main': 'Principal',
    'branches.locked_by_subscription': 'Bloqueada (sin acceso operativo)',
    'branches.name_required': 'El nombre de la sucursal es obligatorio',
    'branches.duplicate_name': 'Ya existe una sucursal con ese nombre',
    'branches.auth_required': 'Debes estar autenticado para gestionar sucursales',
    'branches.update_success': 'actualizada correctamente',
    'branches.create_success': 'creada correctamente',
    'branches.save_error': 'Error al guardar la sucursal',
    'branches.delete': 'Eliminar Sucursal',
    'branches.delete_warning': 'Estás a punto de eliminar:',
    'branches.delete_warning_details': '🚨 ADVERTENCIA:\nSe eliminará:\n\n• Catálogo de vinos completo\n• Inventario y stock\n• Personal registrado\n• Historial y reportes\n• Configuraciones',
    'branches.delete_confirm': '⚠️ CONFIRMACIÓN FINAL',
    'branches.delete_confirm_details': 'ÚLTIMA ADVERTENCIA:\n\nAl eliminar',
    'branches.delete_confirm_list': 'se eliminarán:\n\n• Todo el catálogo de vinos\n• Inventario y stock\n• Personal registrado\n• Historial de ventas\n• Configuraciones\n• Tokens QR activos',
    'branches.delete_confirm_question': '¿CONFIRMAS LA ELIMINACIÓN DEFINITIVA?',
    'branches.delete_success': 'Sucursal Eliminada',
    'branches.delete_success_details': 'y todos sus datos han sido eliminados permanentemente.',
    'branches.delete_error': 'Error al eliminar la sucursal',
    'branches.delete_failed': 'No se pudo eliminar la sucursal',
    'branches.deleting': 'Eliminando…',
    'branches.generate_pdf': 'Generando PDF',
    'branches.pdf_generating': 'Se está generando el catálogo de vinos de',
    'branches.pdf_generating_note': 'Esto puede tardar unos momentos.',
    'branches.pdf_generated': 'PDF Generado',
    'branches.pdf_exported': 'Catálogo de',
    'branches.pdf_exported_success': 'exportado exitosamente.',
    'branches.continue_deletion': 'Continuar con eliminación',
    'branches.cancel_deletion': 'Cancelar eliminación',
    'branches.generate_pdf_continue': 'Generar PDF y continuar',
    'branches.delete_without_pdf': 'Eliminar sin PDF',
    
    // Botones y acciones
    'btn.save': 'Guardar',
    'btn.cancel': 'Cancelar',
    'btn.delete': 'Eliminar',
    'btn.edit': 'Editar',
    'btn.add': 'Agregar',
    'btn.close': 'Cerrar',
    'btn.confirm': 'Confirmar',
    'btn.back': 'Volver',
    'btn.next': 'Siguiente',
    'btn.finish': 'Finalizar',
    
    // Mensajes
    'msg.success': 'Operación exitosa',
    'msg.error': 'Error',
    'msg.limit_reached': 'Límite alcanzado',
    'msg.loading': 'Cargando...',
    'msg.no_data': 'No hay datos disponibles',
    'msg.confirm_delete': '¿Estás seguro de eliminar?',
    
    // Errores comunes
    'common.error': 'Error',
    'common.try_again': 'Intenta de nuevo más tarde',
    
    // Autenticación y permisos
    'auth.access_restricted': 'Acceso Restringido',
    'auth.no_permission': 'No tienes permisos para realizar esta acción.',
    
    // Configuración
    'settings.title': 'Configuración',
    'settings.language': 'Idioma',
    'settings.logout': 'Cerrar Sesión',
    'settings.delete_account': 'Eliminar Cuenta',
    'settings.account': 'Cuenta',
    'settings.actions': 'Acciones',
    'settings.user': 'Usuario',
    'settings.role': 'Rol',
    'settings.back': 'Volver',
    'settings.logout_confirm': '¿Estás seguro de que deseas cerrar sesión?',
    'settings.delete_confirm_owner': '⚠️ ADVERTENCIA CRÍTICA ⚠️\n\nEliminar tu cuenta como Owner eliminará PERMANENTEMENTE:\n\n• Toda tu información personal\n• Todos tus pagos y suscripciones\n• Todas las cuentas de tu staff\n• Todos los exámenes de cata creados\n• Todos los vinos agregados a tu catálogo\n• Todas las sucursales asociadas\n• Todo el historial de ventas e inventario\n\nEsta acción NO se puede deshacer.\n\nPara confirmar, escribe "CONFIRMAR" en mayúsculas:',
    'settings.delete_confirm_staff': '⚠️ ADVERTENCIA ⚠️\n\nEliminar tu cuenta eliminará:\n\n• Tu información personal\n• Tu acceso a esta unidad\n\nDespués de eliminar tu cuenta, necesitarás recibir un nuevo código QR de un administrador para acceder a esta unidad nuevamente.\n\nEsta acción NO se puede deshacer.\n\nPara confirmar, escribe "CONFIRMAR" en mayúsculas:',
    'settings.delete_owner_title': '⚠️ Eliminar Cuenta de Owner',
    'settings.delete_staff_title': '⚠️ Eliminar Cuenta',
    'settings.confirm_placeholder': 'Escribe CONFIRMAR',
    'settings.delete_success': 'Tu cuenta ha sido eliminada exitosamente.',
    'settings.legal_section': 'Legal y privacidad',
    'settings.privacy_policy': 'Política de privacidad',
    'settings.terms_of_service': 'Términos del servicio',
    'settings.support': 'Soporte',
    'settings.link_open_error': 'No se pudo abrir el enlace. Comprueba tu conexión e inténtalo de nuevo.',
    
    // Admin Dashboard
    'admin.title': 'Panel de Administración',
    'admin.branch_current': 'Sucursal Actual:',
    'admin.branch_none': 'Sin sucursal',
    'admin.branch_select': 'Seleccionar Sucursal',
    'admin.branch_changed': 'Sucursal Cambiada',
    'admin.branch_managing': 'Ahora estás gestionando:',
    'admin.branch_change': 'Cambiar',
    'admin.branch_readonly': 'Solo lectura',
    'admin.close_modal': 'Cerrar',
    'admin.menu_title': 'Funciones Administrativas',
    'admin.global_catalog': 'Catálogo Cellarium',
    'admin.global_catalog_sub': 'Importar vinos de base de datos',
    'admin.scan_bottle': 'Ingreso manual de botella',
    'admin.scan_bottle_sub': 'Agregar vino a tu menú',
    'admin.inventory': 'Inventario y Análisis',
    'admin.inventory_sub': 'Stock, ventas, reportes, comparativas',
    'admin.qr_generation': 'Generación de QR',
    'admin.qr_generation_sub': 'QR para comensales e invitaciones',
    'admin.tasting_exams': 'Catas y Degustaciones',
    'admin.tasting_exams_sub': 'Crear y gestionar exámenes de degustación',
    'admin.users': 'Gestión de Usuarios',
    'admin.users_sub': 'Aprobar, asignar roles y permisos',
    'admin.branches': 'Gestión de Sucursales',
    'admin.branches_sub': 'Crear, editar, eliminar sucursales',
    'admin.subscriptions': 'Suscripciones',
    'admin.subscriptions_sub': 'Planes y facturación',
    'admin.settings': 'Configuración',
    'admin.settings_sub': 'Cerrar sesión y eliminar cuenta',
    'admin.feature_locked': 'Función Bloqueada',
    'admin.feature_locked_msg': 'Esta función no está disponible en tu plan actual. Actualiza tu suscripción para acceder.',
    'admin.view_plans': 'Ver Planes',
    'admin.requires_subscription': '⚠️ Requiere suscripción',
    'admin.error_no_branch': 'Debes seleccionar una sucursal primero',
    
    // Features (para suscripciones)
    'features.inventory': 'Inventario y Análisis',
    'features.inventory_desc': 'Gestión de stock, ventas, reportes y comparativas',
    'features.tastings': 'Catas y Degustaciones',
    'features.tastings_desc': 'Crear y gestionar exámenes de degustación',
    'features.branches_additional': 'Gestión de Sucursales adicionales',
    'features.branches_additional_desc': 'Crear y gestionar múltiples sucursales',
    'features.reports_basic': 'Reportes Básicos',
    'features.reports_basic_desc': 'Reportes básicos de ventas e inventario',
    'features.reports_full': 'Reportes Completos',
    'features.reports_full_desc': 'Reportes avanzados y análisis detallados',
    'features.exports': 'Exportación de Datos',
    'features.exports_desc': 'Exportar datos en diferentes formatos',
    'features.branding_powered_by': 'Branding "Powered by Cellarium"',
    'features.branding_powered_by_desc': 'Marca visible en plan gratuito',
    
    // Mensajes de enforcement de suscripciones
    'subscription.auth_required': 'Se requiere autenticación',
    'subscription.feature_blocked': 'Esta función no está disponible en tu plan actual',
    'subscription.wine_limit_reached': 'Límite de vinos alcanzado para tu plan de suscripción',
    'subscription.branch_limit_reached': 'Límite de sucursales alcanzado para tu plan de suscripción',
    'subscription.manager_limit_reached': 'Límite de gerentes alcanzado para tu plan de suscripción',
    'subscription.action_blocked': 'Esta acción no está permitida con tu suscripción actual',
    'subscription.limit_title': 'Límite de Suscripción Alcanzado',
    'subscription.limit_message': 'Has alcanzado el límite permitido por tu plan actual. Actualiza tu suscripción para continuar.',
    'subscription.limit_branches_message': 'Has alcanzado el límite de sucursales ({current}/{limit}). Contrata sucursales adicionales en Suscripciones.',
    'subscription.view_plans': 'Ver Planes',
    'subscription.restricted_title': 'Acceso Restringido',
    'subscription.only_owner_msg': 'Esta función solo está disponible para el dueño de la cuenta.',

    // Subscription screen (SubscriptionsScreen)
    'subscription.screen_title': 'Suscripciones',
    'subscription.status_current': 'Estado actual',
    'subscription.current_plan_title': 'Plan actual',
    'subscription.status_card_tagline_free': 'Ideal para comenzar con una sucursal.',
    'subscription.status_label': 'Estado',
    'subscription.status_active_value': 'Activa',
    'subscription.status_cancel_scheduled_value': 'Cancelada (se desactiva al final del periodo)',
    'subscription.status_free_value': 'Gratis',
    'subscription.active': 'Activo',
    'subscription.yes': 'Sí',
    'subscription.no': 'No',
    'subscription.renews': 'Renueva',
    'subscription.renews_on': 'Se renueva el',
    'subscription.expires': 'Expira',
    'subscription.expires_on': 'Expira el',
    'subscription.deactivates_on': 'Se desactiva el',
    'subscription.status_canceled_value': 'Cancelada',
    'subscription.access_until': 'Acceso hasta',
    'subscription.no_renewal': 'No se renueva',
    'subscription.cancel_scheduled_on': 'Cancelación programada',
    'subscription.addons_branches': 'Sucursales adicionales',
    'subscription.business_includes_branches':
      'Tu plan incluye 1 sucursal base; las adicionales se facturan aparte.',
    'subscription.total_branches_now': 'Actualmente tienes {count} sucursales en total.',
    'subscription.addon_branches_label': 'Sucursales adicionales',
    'subscription.save_addons': 'Actualizar sucursales adicionales',
    'subscription.cta_upgrade': 'Mejorar',
    'subscription.upgrade_section_title': 'Mejorar plan',
    'subscription.recommended_badge': 'Recomendado',
    'subscription.addon_intro_short': 'Sucursales extra: {price}/mes c/u.',
    'subscription.loading_upgrade': 'Abriendo checkout…',
    'subscription.current_addons': 'Sucursales adicionales actuales:',
    'subscription.new_monthly_total': 'Total mensual nuevo:',
    'subscription.refresh': 'Actualizar',
    'subscription.addon_title': 'Sucursales adicionales',
    'subscription.addon_block_intro_1': 'Tu plan incluye 1 sucursal base.',
    'subscription.addon_block_intro_2': 'Puedes agregar sucursales adicionales por {price} MXN al mes cada una.',
    'subscription.addon_quantity_label': 'Cantidad',
    'subscription.addon_extra_monthly_label': 'Costo adicional mensual',
    'subscription.addon_additional_active_0': 'Actualmente no tienes sucursales adicionales activas.',
    'subscription.addon_additional_active_1': 'Actualmente tienes 1 sucursal adicional activa.',
    'subscription.addon_additional_active_n': 'Actualmente tienes {count} sucursales adicionales activas.',
    'subscription.addon_total_capacity_0': 'No tienes sucursales adicionales contratadas; tu plan incluye acceso a {total} sucursales en total.',
    'subscription.addon_total_capacity_1': 'Actualmente tienes 1 sucursal adicional, lo que te permite administrar {total} sucursales en total.',
    'subscription.addon_total_capacity_n': 'Actualmente tienes {additional} sucursales adicionales, lo que te permite administrar {total} sucursales en total.',
    'subscription.addon_breakdown_title': 'Desglose mensual',
    'subscription.addon_monthly_summary_title': 'Resumen mensual',
    'subscription.addon_breakdown_business_plan': 'Plan base',
    'subscription.addon_breakdown_additional': 'Sucursales adicionales',
    'subscription.addon_breakdown_estimated_total': 'Total mensual',
    'subscription.addon_price_per': 'MXN/mes por sucursal adicional.',
    'subscription.addon_current': 'Actual:',
    'subscription.update_addons': 'Actualizar sucursales adicionales',
    'subscription.manage': 'Cancelar suscripción',
    'subscription.upgrade_plan': 'Mejorar plan',
    'subscription.cta_upgrade_to_business': 'Actualizar a Business',
    'subscription.pro_upgrade_title': 'Crece con Business',
    'subscription.pro_upgrade_body':
      'Business está diseñado para restaurantes que necesitan operar en múltiples sucursales y escalar su catálogo.',
    'subscription.pro_upgrade_bullet_0': '3 sucursales incluidas',
    'subscription.pro_upgrade_bullet_1': 'Vinos ilimitados',
    'subscription.pro_upgrade_bullet_2': 'Sucursales adicionales disponibles',
    'subscription.pro_upgrade_bullet_3': 'Ideal para operación multi-sucursal',
    'subscription.pro_upgrade_bullet_2_ios':
      'Facturación y cambios de plan: Ajustes de App Store / cuenta Apple (en iOS no usamos el portal web Stripe).',
    'subscription.pro_upgrade_bullet_3_ios':
      'Business en esta app incluye 3 sucursales; sucursales extra solo con suscripción web (Stripe) en Android o escritorio.',
    'subscription.pro_compare_title': 'Comparar planes',
    'subscription.pro_compare_pro_label': 'PRO',
    'subscription.pro_compare_business_label': 'BUSINESS',
    'subscription.pro_compare_pro_line_0': '1 sucursal',
    'subscription.pro_compare_pro_line_1': 'Hasta 100 vinos',
    'subscription.pro_compare_business_line_0': '3 sucursales incluidas',
    'subscription.pro_compare_business_line_1': 'Vinos ilimitados',
    'subscription.pro_compare_business_line_2': 'Sucursales adicionales disponibles',
    'subscription.pro_compare_business_line_2_ios':
      'Sucursales extra solo con Stripe (web/Android). En iOS, gestiona la suscripción Apple en App Store.',
    'subscription.cancel': 'Cancelar suscripción',
    'subscription.plan_current': 'Plan actual',
    'subscription.includes': 'Incluye:',
    'subscription.not_includes': 'No incluye:',
    'subscription.subscribe_cta': 'Suscribirme',
    'subscription.plan_name.cafe': 'Cafe',
    'subscription.plan_name.bistro': 'Bistro',
    'subscription.plan_name.trattoria': 'Trattoria',
    'subscription.plan_name.grand_maison': 'Grand Maison',
    'subscription.period_month': 'mes',
    'subscription.price_free': 'Gratis',
    'subscription.error_no_session': 'No hay sesión activa',
    'subscription.confirm_subscribe': 'Confirmar Suscripción',
    'subscription.confirm_subscribe_message': '¿Deseas suscribirte al plan "{plan}" por',
    'subscription.cta_subscribe': 'Suscribirse',
    'subscription.no_subscription': 'Sin Suscripción',
    'subscription.no_subscription_message': 'No tienes una suscripción activa. Por favor suscríbete a un plan primero.',
    'subscription.error_generic': 'Hubo un problema al procesar tu solicitud. Intenta de nuevo.',
    'subscription.alert_ok': 'OK',
    'subscription.alert_open_portal': 'Abrir portal',
    'subscription.alert_no': 'No',
    'subscription.cancel_confirm_title': 'Cancelar suscripción',
    'subscription.cancel_confirm_message': 'La cancelación se gestiona desde el portal de Stripe. Ahí podrás cancelar o cambiar tu plan. ¿Abrir portal?',
    'subscription.select_plan_first': 'Por favor selecciona un plan',
    'subscription.plan_free_title': 'Plan Gratis',
    'subscription.plan_free_already': 'Ya estás en el plan gratuito',
    'subscription.plan_invalid_checkout': 'Plan no válido para checkout',
    'subscription.already_subscribed_title': 'Ya tienes suscripción',
    'subscription.already_subscribed_message':
      'Para otros cambios de plan o facturación, usa «Cancelar suscripción» en esta pantalla y sigue los pasos.',
    'subscription.already_subscribed_message_ios':
      'Para cambiar o cancelar usa Administrar suscripción. Si pagaste con Apple, se abre la gestión en App Store (no el portal Stripe).',
    'subscription.addon_confirm_title': 'Confirmar sucursales adicionales',
    'subscription.addon_confirm_body': 'Vas a actualizar tus sucursales adicionales a',
    'subscription.addon_confirm_cost_per_branch': 'Costo por sucursal adicional',
    'subscription.addon_confirm_extra_monthly': 'Cargo mensual adicional estimado',
    'subscription.addon_confirm_next_invoice': 'Este cambio se reflejará en tu próxima factura (Stripe).',
    'subscription.addon_confirm_no_proration': 'No se aplicará prorrateo hoy (proration_behavior=none).',
    'subscription.addon_confirm_remove_note': 'Se quitarán las sucursales adicionales contratadas. Tus sucursales incluidas en el plan siguen igual. Las sucursales extra quedarán bloqueadas hasta que ajustes.',
    'subscription.confirm': 'Confirmar',
    'subscription.update_failed_message': 'No se pudo actualizar. Intenta de nuevo.',
    'subscription.confirm_update_addons_title': 'Confirmar Actualización',
    'subscription.confirm_update_addons_message': '¿Actualizar sucursales adicionales a',
    'subscription.update_success_title': 'Actualización Exitosa',
    'subscription.update_success_message': 'Sucursales adicionales actualizadas a',
    'subscription.profile_loading_retry': 'No se pudo cargar el perfil. Reintentando…',
    'subscription.retry': 'Reintentar',
    'subscription.loading_subscribe': 'Procesando suscripción…',
    'subscription.loading_portal': 'Abriendo portal…',
    'subscription.loading_save_additional_branches': 'Guardando sucursales adicionales…',
    'subscription.apple_manage_title': 'Gestionar suscripción (App Store)',
    'subscription.apple_manage_message':
      'Las suscripciones contratadas con Apple se administran en Ajustes > Apple ID > Suscripciones, o desde la página de cuenta de Apple. No usamos el portal web de Stripe para facturación Apple.',
    'subscription.apple_manage_open': 'Abrir cuenta Apple',
    'subscription.apple_restore': 'Restaurar compras',
    'subscription.apple_loading_purchase': 'Procesando compra en App Store…',
    'subscription.apple_loading_restore': 'Restaurando compras…',
    'subscription.apple_loading_sync': 'Sincronizando suscripción…',
    'subscription.apple_sync_lapsed_title': 'Suscripción no activa',
    'subscription.apple_sync_lapsed_message':
      'El recibo indica que la suscripción ya no está vigente. Se actualizó tu plan en Cellarium.',
    'subscription.apple_success_title': 'Listo',
    'subscription.apple_success_message': 'Tu plan se sincronizó correctamente.',
    'subscription.apple_confirm_title': '¿Suscribirte con Apple?',
    'subscription.apple_confirm_message':
      'Se abrirá el flujo de pago de Apple (App Store). El precio final es el de tu región.',
    'subscription.apple_backend_retry_hint':
      'Si fue un fallo temporal de red o servidor, puedes reintentar. La transacción no se cierra en el dispositivo hasta que el servidor confirme.',
    'subscription.apple_sync_unclear_message':
      'No recibimos una confirmación clara del servidor. No se finalizó la transacción en el dispositivo; reintenta con conexión estable.',
    'subscription.apple_restore_ios_hint':
      'Las suscripciones contratadas con Apple se administran en Ajustes > Apple ID > Suscripciones.',
    'subscription.branch_reduction_blocked':
      'No puedes reducir sucursales adicionales porque tienes más sucursales activas de las permitidas.',
    'subscription.verify_email_to_update_branches':
      'Verifica tu correo para actualizar las sucursales adicionales de tu suscripción.',
    'subscription.verify_email_to_continue': 'Verifica tu correo para continuar.',
    'subscription.addons_stripe_only':
      'Las sucursales adicionales con cantidad variable solo aplican con facturación Stripe (web/Android).',
    'subscription.addon_breakdown_base_plan': 'Plan base (detalle en portal / factura)',
    'subscription.ios_branch_addon_intro':
      'Paquetes de sucursales adicionales vía Apple (1 o 3). Tras pagar, sincronizamos con el servidor.',
    'subscription.ios_branch_addon_1': '+1 sucursal adicional (Apple)',
    'subscription.ios_branch_addon_3': '+3 sucursales adicionales (Apple)',
    'subscription.qty_validation': 'La cantidad debe ser un número entre 0 y 50',
    'subscription.plan_updated_title': 'Plan actualizado',
    'subscription.plan_updated_message': 'Los cambios ya están aplicados en tu cuenta.',
    'subscription.upgrade_success_title': 'Plan actualizado',
    'subscription.upgrade_success_message':
      'Tu suscripción se actualizó correctamente. Los cambios de tu plan ya están activos.',
    'subscription.upgrade_done_cta': 'Entendido',
    'subscription.upgrade_receipt_optional': 'Ver comprobante de pago',
    'subscription.addon_saved_modal_title': 'Sucursales actualizadas',
    'subscription.addon_saved_modal_body':
      'Quedaste con {qty} sucursal(es) adicional(es). Los cambios se reflejan en tu próxima facturación.',
    'subscription.cta_update': 'Actualizar',
    'common.na': 'N/A',
    'subscription.plan.cafe.features.0': '1 sucursal base',
    'subscription.plan.cafe.features.1': 'Hasta 10 vinos y 10 cócteles',
    'subscription.plan.cafe.features.2': '1 miembro de staff adicional',
    'subscription.plan.cafe.features.3': 'QR y gestión básica',
    'subscription.plan.cafe.blocked.0': 'Inventario y análisis',
    'subscription.plan.cafe.blocked.1': 'Catas y degustaciones',
    'subscription.plan.bistro.features.0': '50 vinos',
    'subscription.plan.bistro.features.1': '50 cócteles',
    'subscription.plan.bistro.features.2': 'Hasta 3 miembros de staff',
    'subscription.plan.bistro.features.3': 'Funciones premium desbloqueadas',
    'subscription.plan.trattoria.features.0': '150 vinos',
    'subscription.plan.trattoria.features.1': '75 cócteles',
    'subscription.plan.trattoria.features.2': 'Staff ilimitado',
    'subscription.plan.grand_maison.features.0': 'Vinos ilimitados',
    'subscription.plan.grand_maison.features.1': 'Cócteles ilimitados',
    'subscription.simulate_title': 'Simular Pago (DEV ONLY)',
    'subscription.simulate_message': '¿Simular pago exitoso para',
    'subscription.simulate_cta': 'Simular',
    'subscription.simulate_success': 'Simulación Exitosa',
    'subscription.simulate_success_message': 'activado (simulado).',

    'admin.cocktail_menu': 'Menú de Coctelería',
    'admin.cocktail_menu_sub': 'Gestionar bebidas exclusivas de la sucursal',
    
    // Cocktail Menu
    'cocktail.title': 'Menú de Coctelería',
    'cocktail.subtitle': 'Gestiona las bebidas exclusivas de esta sucursal',
    'cocktail.add_drink': 'Agregar Bebida',
    'cocktail.edit_drink': 'Editar Bebida',
    'cocktail.delete_drink': 'Eliminar Bebida',
    'cocktail.name': 'Nombre de la Bebida',
    'cocktail.name_es': 'Nombre (Español)',
    'cocktail.name_en': 'Nombre (Inglés)',
    'cocktail.description': 'Descripción',
    'cocktail.description_es': 'Descripción (Español)',
    'cocktail.description_en': 'Descripción (Inglés)',
    'cocktail.ingredients': 'Ingredientes',
    'cocktail.ingredients_es': 'Ingredientes (Español)',
    'cocktail.ingredients_en': 'Ingredientes (Inglés)',
    'cocktail.ingredient_placeholder': 'Ej: Ron, Limón, Azúcar...',
    'cocktail.price': 'Precio',
    'cocktail.price_placeholder': '0.00',
    'cocktail.photo': 'Foto de la Bebida',
    'cocktail.choose_aspect': 'Formato de recorte',
    'cocktail.aspect_3_4': 'Rectangular (3:4)',
    'cocktail.aspect_1_1': 'Cuadrado (1:1)',
    'cocktail.take_photo': 'Tomar Foto',
    'cocktail.select_from_gallery': 'Seleccionar de Galería',
    'cocktail.gallery_line1': 'Elegir de',
    'cocktail.gallery_line2': 'Galería',
    'cocktail.save': 'Guardar Bebida',
    'cocktail.cancel': 'Cancelar',
    'cocktail.delete_confirm': '¿Estás seguro de eliminar esta bebida?',
    'cocktail.delete_success': 'Bebida eliminada correctamente',
    'cocktail.save_success': 'Bebida guardada correctamente',
    'cocktail.save_error': 'Error al guardar la bebida',
    'cocktail.limit_free_10': 'Límite del plan Free: máximo 10 cocteles activos por sucursal. Verifica tu email o actualiza a Pro/Business para ilimitado.',
    'cocktail.delete_error': 'Error al eliminar la bebida',
    'cocktail.name_required': 'El nombre es obligatorio',
    'cocktail.ingredients_required': 'Los ingredientes son obligatorios',
    'cocktail.price_required': 'El precio es obligatorio',
    'cocktail.price_invalid': 'El precio debe ser un número válido',
    'cocktail.no_drinks': 'No hay bebidas en el menú',
    'cocktail.add_first': 'Agrega tu primera bebida',
    'cocktail.beverages_available': 'bebidas disponibles',
    'cocktail.empty_primary': 'Aún no hay bebidas',
    'cocktail.empty_secondary': 'Agrega tu primera creación exclusiva',
    'cocktail.loading': 'Cargando menú...',
    'cocktail.uploading_image': 'Subiendo imagen...',
    'cocktail.permission_required': 'Permiso requerido',
    'cocktail.camera_access': 'Necesitamos acceso a la cámara',
    'cocktail.gallery_access': 'Necesitamos acceso a la galería',
    'cocktail.error_capture': 'Error al capturar la imagen',
    'cocktail.error_select': 'Error al seleccionar la imagen',
    'cocktail.error_upload': 'Error al subir la imagen',
    'cocktail.error_compress': 'Error al comprimir la imagen',
    'cocktail.compressing_image': 'Comprimiendo imagen...',
    
    // Wine Management
    'wine_mgmt.title': 'Ingreso manual de botella',
    'wine_mgmt.hero_description': 'Agrega una foto frontal y completa los datos básicos.',
    'wine_mgmt.photo_hint': 'Bien enfocada y sin reflejos.',
    'wine_mgmt.front_label': 'Anverso de la etiqueta (obligatorio)',
    'wine_mgmt.back_label': 'Reverso de la etiqueta (opcional)',
    'wine_mgmt.additional_photos': 'Fotos adicionales (opcional)',
    'wine_mgmt.pro_camera': 'Cámara Pro',
    'wine_mgmt.gallery': 'Galería',
    'wine_mgmt.process_ai': 'Procesar con IA',
    'wine_mgmt.processing': 'Guardando...',
    'wine_mgmt.processing_label': 'Guardando...',
    'wine_mgmt.front_label_camera': 'Anverso de la etiqueta',
    'wine_mgmt.back_label_camera': 'Reverso de la etiqueta',
    'wine_mgmt.camera_auto_capture': 'La cámara detectará automáticamente la etiqueta y capturará cuando esté estable',
    'wine_mgmt.close': 'Cerrar',
    'wine_mgmt.save_wine': 'Guardar vino',
    'wine_mgmt.permission_required': 'Permiso requerido',
    'wine_mgmt.gallery_access': 'Necesitamos acceso a la galería',
    'wine_mgmt.camera_access': 'Necesitamos acceso a la cámara para capturar la etiqueta',
    'wine_mgmt.error_select_front': 'No se pudo seleccionar la imagen del anverso',
    'wine_mgmt.error_select_back': 'No se pudo seleccionar la imagen del reverso',
    'wine_mgmt.error_capture_front': 'No se pudo capturar la imagen del anverso',
    'wine_mgmt.error_capture_back': 'No se pudo capturar la imagen del reverso',
    'wine_mgmt.error_select_additional': 'No se pudo seleccionar la imagen adicional',
    'wine_mgmt.error_no_front': 'Debes capturar al menos la foto del anverso de la etiqueta',
    'wine_mgmt.error_process_labels': 'No se pudieron procesar las etiquetas. Intenta de nuevo.',
    'wine_mgmt.error_capture': 'No se pudo capturar la imagen',
    'wine_mgmt.error_process': 'No se pudo procesar la etiqueta. Intenta de nuevo.',
    'wine_mgmt.error_camera': 'Error de Cámara',
    'wine_mgmt.missing_fields': 'Campos obligatorios faltantes',
    'wine_mgmt.missing_fields_msg': 'Por favor completa los siguientes campos antes de agregar el vino al catálogo:',
    'wine_mgmt.understood': 'Entendido',
    'wine_mgmt.error_stock': 'Por favor ingresa el stock inicial',
    'wine_mgmt.error_branch': 'No hay sucursal seleccionada',
    'wine_mgmt.error_auth': 'Usuario no autenticado',
    'wine_mgmt.success_title': '✅ Vino registrado',
    'wine_mgmt.success_msg': 'ha sido agregado al catálogo con',
    'wine_mgmt.success_bottles': 'botellas en stock.',
    'wine_mgmt.add_another': 'Agregar otro',
    'wine_mgmt.view_catalog': 'Ver catálogo',
    'wine_mgmt.error_save': 'No se pudo guardar el vino:',
    'wine_mgmt.bottle_image': '🖼️ Imagen de la Botella',
    'wine_mgmt.select_image': 'Selecciona una imagen sugerida o sube tu propia foto',
    'wine_mgmt.suggested_images': 'Imágenes sugeridas por IA',
    'wine_mgmt.upload_own': '📤 Subir mi propia imagen',
    'wine_mgmt.continue': 'Continuar',
    'wine_mgmt.alcohol_content': 'Contenido de alcohol',
    'wine_mgmt.description': 'Descripción',
    'wine_mgmt.wine_type': 'Tipo de vino',
    'wine_mgmt.name': 'Nombre del vino',
    'wine_mgmt.winery': 'Bodega',
    'wine_mgmt.grape_variety': 'Tipo de uva',
    'wine_mgmt.vintage': 'Cosecha',
    'wine_mgmt.region': 'Región',
    'wine_mgmt.country': 'País',
    'wine_mgmt.section_wine_info': 'Información del Vino',
    'wine_mgmt.section_prices': 'Precios y Stock',
    'wine_mgmt.price_glass': 'Precio por Copa',
    'wine_mgmt.price_bottle': 'Precio por Botella',
    'wine_mgmt.price_bottle_optional': 'Precio por Botella (opcional)',
    'wine_mgmt.initial_stock': 'Stock Inicial',
    'wine_mgmt.select_image_btn': 'Seleccionar imagen',
    'wine_mgmt.change_image': 'Cambiar imagen',
    'wine_mgmt.tasting_notes': 'Notas de cata',
    'wine_mgmt.pairings': 'Maridajes',
    'wine_mgmt.serving_temp': 'Temperatura de servicio',
    'wine_mgmt.alcohol_pct': '% Alcohol',
    'wine_mgmt.stock_help': 'Botellas en stock. Cambios posteriores se hacen desde Control de Inventario.',
    'wine_mgmt.placeholder_name': 'Ej: Château Margaux',
    'wine_mgmt.placeholder_grape': 'Ej: Cabernet Sauvignon',
    'wine_mgmt.placeholder_region': 'Ej: Bordeaux',
    'wine_mgmt.placeholder_country': 'Ej: Francia',
    'wine_mgmt.placeholder_pairings': 'Carnes rojas, quesos, etc.',
    'wine_mgmt.placeholder_temp': '16-18°C',
    'wine_mgmt.placeholder_desc': 'Descripción general del vino...',
    'wine_mgmt.placeholder_tasting': 'Aromas, sabores, textura...',
    'wine_mgmt.section_sensory': 'Perfil sensorial',
    'wine_mgmt.sensory_help': 'Opcional. Valores del 1 al 5 que se verán en la ficha del vino (Cuerpo, Dulzor, Acidez, Tanicidad).',
    
    // Global Wine Catalog
    'global_catalog.title': 'Catálogo Cellarium',
    'global_catalog.subtitle': 'vinos disponibles • Página',
    'global_catalog.of': 'de',
    'global_catalog.search': 'Buscar',
    'global_catalog.search_placeholder': 'Buscar vino...',
    'global_catalog.all_wines': 'Todos los vinos',
    'global_catalog.red': 'Tintos',
    'global_catalog.white': 'Blancos',
    'global_catalog.rose': 'Rosados',
    'global_catalog.sparkling': 'Espumosos',
    'global_catalog.dessert': 'Vinos de Postre',
    'global_catalog.fortified': 'Fortificados',
    'global_catalog.view_details': 'Ver Ficha',
    'global_catalog.add': 'Agregar',
    'global_catalog.already_added': 'Vino ya agregado',
    'global_catalog.loading': 'Cargando catálogo...',
    'global_catalog.no_wines': 'No se encontraron vinos',
    'global_catalog.no_image': 'Sin imagen',
    'global_catalog.vintage': 'Añada:',
    'global_catalog.loading_details': 'Cargando ficha...',
    'global_catalog.country': 'País:',
    'global_catalog.region': 'Región:',
    'global_catalog.color': 'Color:',
    'global_catalog.varietals': 'Varietales',
    'global_catalog.alcohol': 'Graduación:',
    'global_catalog.volume': 'Volumen:',
    'global_catalog.closure': 'Cierre:',
    'global_catalog.style': 'Estilo:',
    'global_catalog.appellation': 'Denominación:',
    'global_catalog.flavors': 'Sabores',
    'global_catalog.tasting_profile': 'Perfil de Cata',
    'global_catalog.pairings': 'Maridajes',
    'global_catalog.vinification': 'Vinificación',
    'global_catalog.close': 'Cerrar',
    'global_catalog.add_to_catalog': 'Agregar al Catálogo',
    'global_catalog.restaurant_name_required': 'Nombre del restaurante requerido',
    'global_catalog.restaurant_name_owner_msg': 'Antes de agregar vinos debes definir el nombre de tu restaurante o centro de consumo. Puedes editarlo desde Gestión de Sucursales.',
    'global_catalog.restaurant_name_staff_msg': 'El owner debe definir el nombre del restaurante o centro de consumo antes de agregar vinos. Contacta al responsable para que lo configure.',
    'global_catalog.later': 'Más tarde',
    'global_catalog.go_to_management': 'Ir a Gestión',
    'global_catalog.understood': 'Entendido',
    'global_catalog.error_load': 'Error al cargar vinos',
    'global_catalog.error_unknown': 'Error desconocido',
    'global_catalog.error_details': 'No se pudieron cargar los detalles del vino',
    'global_catalog.error_load_details': 'Error al cargar los detalles',
    'global_catalog.body': 'Cuerpo',
    'global_catalog.acidity': 'Acidez',
    'global_catalog.fizziness': 'Burbujas',
    'global_catalog.tannin': 'Taninos',
    'global_catalog.sweetness': 'Dulzor',
  },
  en: {
    // Navigation and menu
    'nav.wine_catalog': 'Wine Catalog',
    'nav.inventory': 'Inventory',
    'nav.analytics': 'Analytics',
    'nav.users': 'Users',
    'nav.branches': 'Branches',
    'nav.qr_generation': 'Generate QR',
    'nav.settings': 'Settings',
    'nav.tasting_exams': 'Tasting Exams',
    
    // Catalog
    'catalog.title': 'Wine Catalog',
    'catalog.search_placeholder': 'Search wines...',
    'catalog.no_wines': 'No wines available',
    'catalog.filter_by_type': 'Filter by type',
    'catalog.filter_by_region': 'Filter by region',
    'catalog.all_types': 'All types',
    'catalog.all_regions': 'All regions',
    'catalog.all': 'All',
    'catalog.by_glass': 'By Glass',
    'catalog.by_bottle': 'By Bottle',
    'catalog.cocktails': 'Cocktails',
    'catalog.red': 'Red',
    'catalog.white': 'White',
    'catalog.rose': 'Rosé',
    'catalog.sparkling': 'Sparkling',
    'catalog.dessert': 'Dessert',
    'catalog.fortified': 'Fortified',
    'catalog.edit_name': 'Edit name',
    'catalog.configure_name': 'Configure name',
    'catalog.define_restaurant': 'Define your restaurant name',
    'catalog.restaurant_name_placeholder': 'Restaurant name',
    'catalog.sort_asc': 'A → Z',
    'catalog.loading': 'Loading catalog...',
    'catalog.success': 'Success',
    'catalog.glass_sale_enabled': 'Glass sale enabled.',
    'catalog.glass_sale_disabled': 'Glass sale disabled.',
    'catalog.error': 'Error',
    'catalog.error_update_config': 'Could not update configuration',
    'catalog.no_active_branch': 'No active branch selected',
    'catalog.invalid_price': 'Invalid price',
    'catalog.guest_session_invalid': 'Could not identify your guest session. Please scan the QR again.',
    'catalog.out_of_stock': 'Out of stock',
    'catalog.out_of_stock_title': 'Out of Stock',
    'catalog.out_of_stock_message': 'This wine is not available at the moment',
    'catalog.confirm_purchase': 'Confirm Purchase',
    'catalog.a_bottle': 'a bottle',
    'catalog.a_glass': 'a glass',
    'catalog.want_to_buy': 'Do you want to buy',
    'catalog.of_wine': 'of',
    'catalog.price_label': 'Price',
    'catalog.cancel': 'Cancel',
    'catalog.confirm': 'Confirm',
    'catalog.purchase_success': 'Purchase Successful!',
    'catalog.purchase_success_message': 'Your order has been recorded. Staff will bring it shortly.',
    'catalog.branch_unavailable': 'Branch unavailable',
    'catalog.branch_unavailable_message': 'Could not identify this menu\'s branch. Please scan the QR again or try again.',
    'catalog.owner_unknown': 'Could not identify this menu\'s owner. Please scan the QR again or try again.',
    'catalog.purchase_error': 'Could not process purchase. Please try again.',
    'catalog.guest_back': 'Back',
    'catalog.guest_scan_again': 'Scan another QR',
    'catalog.guest_token_missing': 'Guest token missing.',
    'catalog.guest_code_expired': 'This code has expired or is no longer valid. Request a new one.',
    'catalog.branch_required': 'No branch selected',
    'catalog.branch_required_message': 'Select a branch before editing the name.',
    'catalog.name_required': 'Name required',
    'catalog.name_required_message': 'Enter a name for your restaurant or venue.',
    'catalog.saving': 'Saving...',
    'catalog.save': 'Save',
    'catalog.error_update_branch_name': 'Could not update restaurant name.',
    'catalog.pairings_no_suggested': 'No suggested pairings',
    'catalog.close': 'Close',
    'catalog.session_invalid_title': 'Invalid session',
    'catalog.not_available': 'Not available',
    'catalog.not_available_bottle': 'This wine is not available by bottle.',
    'catalog.not_available_glass': 'This wine is not available by glass.',
    'catalog.branch_name_updated': 'Name updated',
    'catalog.branch_name_updated_message': 'The restaurant name was updated successfully.',
    
    // Wine
    'wine.name': 'Name',
    'wine.winery': 'Winery',
    'wine.vintage': 'Vintage',
    'wine.type': 'Type',
    'wine.region': 'Region',
    'wine.country': 'Country',
    'wine.grape_variety': 'Grape Variety',
    'wine.alcohol_content': 'Alcohol Content',
    'wine.description': 'Description',
    'wine.tasting_notes': 'Tasting Notes',
    'wine.food_pairings': 'Food Pairings',
    'wine.serving_temperature': 'Serving Temperature',
    'wine.price_bottle': 'Bottle Price',
    'wine.price_glass': 'Glass Price',
    'wine.stock': 'Stock',
    'wine.available_by_glass': 'Available by Glass',
    'wine.available_by_bottle': 'Available by Bottle',
    'wine.bottle': 'Bottle',
    'wine.glass': 'Glass',
    'wine.buy_glass': 'Buy Glass',
    'wine.buy_bottle': 'Buy Bottle',
    'wine.recommended_pairings': 'Recommended Pairings:',
    'wine.pairings_modal_heading_premium': 'Pairing recommendations',
    'wine.vintage_label': 'Vintage:',
    'wine.config_glass_sale': 'Configure Glass Sale',
    'wine.glass_sale': 'Glass Sale',
    'wine.enable_glass_sale': 'Enable glass sale for this wine',
    'wine.config_glass_sale_error': 'Please enter a valid price for the glass',
    'wine.suggested_price': 'Suggested price',
    'wine.one_fifth_bottle': '1/5 of bottle price',
    
    // Sensory Card
    'sensory.body': 'Body',
    'sensory.sweetness': 'Sweetness',
    'sensory.acidity': 'Acidity',
    'sensory.tannin': 'Tannin',
    'sensory.intensity': 'Intensity',
    'sensory.fizziness': 'Fizziness',
    'sensory.light': 'Light',
    'sensory.medium': 'Medium',
    'sensory.full': 'Full',
    'sensory.dry': 'Dry',
    'sensory.sweet': 'Sweet',
    'sensory.low': 'Low',
    'sensory.high': 'High',
    'sensory.subtle': 'Subtle',
    'sensory.intense': 'Intense',
    'sensory.still': 'Still',
    'sensory.sparkling': 'Sparkling',
    
    // Inventory
    'inventory.title': 'Inventory Management',
    'inventory.low_stock': 'Low Stock',
    'inventory.out_of_stock': 'Out of Stock',
    'inventory.add_wine': 'Add Wine',
    'inventory.edit_wine': 'Edit Wine',
    'inventory.delete_wine': 'Delete Wine',
    'inventory.stock_quantity': 'Stock Quantity',
    'inventory.adjust_stock': 'Adjust Stock',
    
    // Users
    'users.title': 'User Management',
    'users.pending_approval': 'Pending Approval',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.approve': 'Approve',
    'users.reject': 'Reject',
    'users.role': 'Role',
    'users.status': 'Status',
    'users.no_permissions': 'You do not have permission to access this screen',
    'users.approve_user': 'Approve User',
    'users.select_role': 'Select role for',
    'users.approved_success': 'approved as',
    'users.reject_user': 'Reject User',
    'users.reject_confirm': 'Do you want to reject the request from',
    'users.rejected': 'Rejected',
    'users.rejected_success': 'Request from',
    'users.delete_user': 'Delete User',
    'users.delete_confirm': 'Are you sure you want to permanently delete',
    'users.delete_warning': 'This action cannot be undone.',
    'users.cannot_delete_other_org': 'You cannot delete users from other organizations',
    'users.cannot_delete_same_level': 'You can only delete users with a role lower than yours',
    'users.cannot_delete_other_branch': 'You can only delete users from your branch',
    'users.no_delete_permission': 'You do not have permission to delete users',
    'users.cannot_delete_owner': 'Cannot delete the Owner',
    'users.change_role': 'Change Role',
    'users.select_new_role': 'Select new role for',
    'users.role_changed': 'Role updated successfully',
    'users.no_assign_permission': 'You do not have permission to assign roles',
    'users.approve_error': 'Could not approve user',
    'users.delete_error': 'Could not delete user',
    'users.deleted_success': 'has been successfully removed.',
    'users.requesting': 'Requesting:',
    'users.branch': 'Branch:',
    'users.all_branches': 'All branches',
    'users.pending_requests': 'Pending Requests',
    'users.cannot_change_owner_role': 'Cannot change Owner role',
    'users.no_modify_permission': 'You do not have permission to modify the role of',
    'users.no_assign_role_permission': 'You do not have permission to assign the role of',
    'users.change_role_confirm': 'Change role of',
    'users.change_role_from_to': 'from',
    'users.change_role_to': 'to',
    'users.role_updated': 'Role of',
    'users.role_updated_to': 'updated to',
    'users.current': 'Current',
    'users.current_role': 'Current role:',
    
    // Branches
    'branches.title': 'Branch Management',
    'branches.subtitle': 'Manage restaurant locations',
    'branches.add_branch': 'Add Branch',
    'branches.create_branch': 'Create New Branch',
    'branches.edit_branch': 'Edit Branch',
    'branches.name': 'Name',
    'branches.address': 'Address',
    'branches.phone': 'Phone',
    'branches.email': 'Email',
    'branches.registered': 'Registered Branches',
    'branches.main': 'Main',
    'branches.locked_by_subscription': 'Locked (no operational access)',
    'branches.name_required': 'Branch name is required',
    'branches.duplicate_name': 'A branch with that name already exists',
    'branches.auth_required': 'You must be authenticated to manage branches',
    'branches.update_success': 'updated successfully',
    'branches.create_success': 'created successfully',
    'branches.save_error': 'Error saving branch',
    'branches.delete': 'Delete Branch',
    'branches.delete_warning': 'You are about to delete:',
    'branches.delete_warning_details': '🚨 WARNING:\nThe following will be deleted:\n\n• Complete wine catalog\n• Inventory and stock\n• Registered staff\n• History and reports\n• Settings',
    'branches.delete_confirm': '⚠️ FINAL CONFIRMATION',
    'branches.delete_confirm_details': 'LAST WARNING:\n\nDeleting',
    'branches.delete_confirm_list': 'will delete:\n\n• Complete wine catalog\n• Inventory and stock\n• Registered staff\n• Sales history\n• Settings\n• Active QR tokens',
    'branches.delete_confirm_question': 'DO YOU CONFIRM THE DEFINITIVE DELETION?',
    'branches.delete_success': 'Branch Deleted',
    'branches.delete_success_details': 'and all its data have been permanently deleted.',
    'branches.delete_error': 'Error deleting branch',
    'branches.delete_failed': 'Could not delete branch',
    'branches.deleting': 'Deleting…',
    'branches.generate_pdf': 'Generating PDF',
    'branches.pdf_generating': 'Generating wine catalog for',
    'branches.pdf_generating_note': 'This may take a few moments.',
    'branches.pdf_generated': 'PDF Generated',
    'branches.pdf_exported': 'Catalog from',
    'branches.pdf_exported_success': 'exported successfully.',
    'branches.continue_deletion': 'Continue with deletion',
    'branches.cancel_deletion': 'Cancel deletion',
    'branches.generate_pdf_continue': 'Generate PDF and continue',
    'branches.delete_without_pdf': 'Delete without PDF',
    
    // Buttons and actions
    'btn.save': 'Save',
    'btn.cancel': 'Cancel',
    'btn.delete': 'Delete',
    'btn.edit': 'Edit',
    'btn.add': 'Add',
    'btn.close': 'Close',
    'btn.confirm': 'Confirm',
    'btn.back': 'Back',
    'btn.next': 'Next',
    'btn.finish': 'Finish',
    
    // Messages
    'msg.success': 'Operation successful',
    'msg.error': 'Error',
    'msg.limit_reached': 'Limit reached',
    'msg.loading': 'Loading...',
    'msg.no_data': 'No data available',
    'msg.confirm_delete': 'Are you sure you want to delete?',
    
    // Common errors
    'common.error': 'Error',
    'common.try_again': 'Please try again later',
    
    // Authentication and permissions
    'auth.access_restricted': 'Access Restricted',
    'auth.no_permission': 'You do not have permission to perform this action.',
    
    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.logout': 'Log Out',
    'settings.delete_account': 'Delete Account',
    'settings.account': 'Account',
    'settings.actions': 'Actions',
    'settings.user': 'User',
    'settings.role': 'Role',
    'settings.back': 'Back',
    'settings.logout_confirm': 'Are you sure you want to log out?',
    'settings.delete_confirm_owner': '⚠️ CRITICAL WARNING ⚠️\n\nDeleting your account as Owner will PERMANENTLY delete:\n\n• All your personal information\n• All your payments and subscriptions\n• All your staff accounts\n• All tasting exams created\n• All wines added to your catalog\n• All associated branches\n• All sales and inventory history\n\nThis action CANNOT be undone.\n\nTo confirm, type "CONFIRMAR" in uppercase:',
    'settings.delete_confirm_staff': '⚠️ WARNING ⚠️\n\nDeleting your account will delete:\n\n• Your personal information\n• Your access to this unit\n\nAfter deleting your account, you will need to receive a new QR code from an administrator to access this unit again.\n\nThis action CANNOT be undone.\n\nTo confirm, type "CONFIRMAR" in uppercase:',
    'settings.delete_owner_title': '⚠️ Delete Owner Account',
    'settings.delete_staff_title': '⚠️ Delete Account',
    'settings.confirm_placeholder': 'Type CONFIRMAR',
    'settings.delete_success': 'Your account has been successfully deleted.',
    'settings.legal_section': 'Legal & privacy',
    'settings.privacy_policy': 'Privacy Policy',
    'settings.terms_of_service': 'Terms of Service',
    'settings.support': 'Support',
    'settings.link_open_error': 'Could not open the link. Check your connection and try again.',
    
    // Admin Dashboard
    'admin.title': 'Administration Panel',
    'admin.branch_current': 'Current Branch:',
    'admin.branch_none': 'No branch',
    'admin.branch_select': 'Select Branch',
    'admin.branch_changed': 'Branch Changed',
    'admin.branch_managing': 'You are now managing:',
    'admin.branch_change': 'Change',
    'admin.branch_readonly': 'Read-only',
    'admin.close_modal': 'Close',
    'admin.menu_title': 'Administrative Functions',
    'admin.global_catalog': 'Cellarium Catalog',
    'admin.global_catalog_sub': 'Import wines from database',
    'admin.scan_bottle': 'Manual wine entry',
    'admin.scan_bottle_sub': 'Add wine to your menu',
    'admin.inventory': 'Inventory & Analytics',
    'admin.inventory_sub': 'Stock, sales, reports, comparisons',
    'admin.qr_generation': 'QR Generation',
    'admin.qr_generation_sub': 'QR codes for diners and invitations',
    'admin.tasting_exams': 'Tastings & Degustations',
    'admin.tasting_exams_sub': 'Create and manage tasting exams',
    'admin.users': 'User Management',
    'admin.users_sub': 'Approve, assign roles and permissions',
    'admin.branches': 'Branch Management',
    'admin.branches_sub': 'Create, edit, delete branches',
    'admin.subscriptions': 'Subscriptions',
    'admin.subscriptions_sub': 'Plans and billing',
    'admin.settings': 'Settings',
    'admin.settings_sub': 'Log out and delete account',
    'admin.feature_locked': 'Feature Locked',
    'admin.feature_locked_msg': 'This feature is not available in your current plan. Upgrade your subscription to access.',
    'admin.view_plans': 'View Plans',
    'admin.requires_subscription': '⚠️ Requires subscription',
    'admin.error_no_branch': 'You must select a branch first',
    
    // Features (for subscriptions)
    'features.inventory': 'Inventory & Analytics',
    'features.inventory_desc': 'Stock management, sales, reports and comparisons',
    'features.tastings': 'Tastings & Degustations',
    'features.tastings_desc': 'Create and manage tasting exams',
    'features.branches_additional': 'Additional Branch Management',
    'features.branches_additional_desc': 'Create and manage multiple branches',
    'features.reports_basic': 'Basic Reports',
    'features.reports_basic_desc': 'Basic sales and inventory reports',
    'features.reports_full': 'Full Reports',
    'features.reports_full_desc': 'Advanced reports and detailed analytics',
    'features.exports': 'Data Export',
    'features.exports_desc': 'Export data in different formats',
    'features.branding_powered_by': 'Branding "Powered by Cellarium"',
    'features.branding_powered_by_desc': 'Visible branding on free plan',
    
    // Subscription enforcement messages
    'subscription.auth_required': 'Authentication required',
    'subscription.feature_blocked': 'This feature is not available in your current plan',
    'subscription.wine_limit_reached': 'Wine limit reached for your subscription plan',
    'subscription.branch_limit_reached': 'Branch limit reached for your subscription plan',
    'subscription.manager_limit_reached': 'Manager limit reached for your subscription plan',
    'subscription.action_blocked': 'This action is not allowed with your current subscription',
    'subscription.limit_title': 'Subscription Limit Reached',
    'subscription.limit_message': 'You have reached the limit allowed by your current plan. Upgrade your subscription to continue.',
    'subscription.limit_branches_message': 'You have reached your branch limit ({current}/{limit}). Add more branches in Subscriptions.',
    'subscription.view_plans': 'View Plans',
    'subscription.restricted_title': 'Access Restricted',
    'subscription.only_owner_msg': 'This feature is only available for the account owner.',

    // Subscription screen (SubscriptionsScreen)
    'subscription.screen_title': 'Subscriptions',
    'subscription.status_current': 'Current status',
    'subscription.current_plan_title': 'Current plan',
    'subscription.status_card_tagline_free': 'Ideal to get started with one branch.',
    'subscription.status_label': 'Status',
    'subscription.status_active_value': 'Active',
    'subscription.status_cancel_scheduled_value': 'Scheduled to cancel',
    'subscription.status_free_value': 'Free',
    'subscription.active': 'Active',
    'subscription.yes': 'Yes',
    'subscription.no': 'No',
    'subscription.renews': 'Renews',
    'subscription.renews_on': 'Renews on',
    'subscription.expires': 'Expires',
    'subscription.expires_on': 'Expires on',
    'subscription.deactivates_on': 'Deactivates on',
    'subscription.status_canceled_value': 'Canceled',
    'subscription.access_until': 'Access until',
    'subscription.no_renewal': 'Will not renew',
    'subscription.cancel_scheduled_on': 'Cancel scheduled',
    'subscription.addons_branches': 'Additional branches',
    'subscription.business_includes_branches':
      'Your plan includes 1 base branch; additional branches are billed separately.',
    'subscription.total_branches_now': 'You currently have {count} total branches.',
    'subscription.addon_branches_label': 'Additional branches',
    'subscription.save_addons': 'Update additional branches',
    'subscription.cta_upgrade': 'Upgrade',
    'subscription.upgrade_section_title': 'Upgrade plan',
    'subscription.recommended_badge': 'Recommended',
    'subscription.addon_intro_short': 'Extra branches: {price}/mo each.',
    'subscription.loading_upgrade': 'Opening checkout…',
    'subscription.current_addons': 'Current additional branches:',
    'subscription.new_monthly_total': 'New monthly total:',
    'subscription.refresh': 'Refresh',
    'subscription.addon_title': 'Additional branches',
    'subscription.addon_block_intro_1': 'Your plan includes 1 base branch.',
    'subscription.addon_block_intro_2': 'You can add more branches for {price} MXN/month each.',
    'subscription.addon_quantity_label': 'Quantity',
    'subscription.addon_extra_monthly_label': 'Additional monthly cost',
    'subscription.addon_additional_active_0': 'You currently have no additional branches active.',
    'subscription.addon_additional_active_1': 'Currently you have 1 additional branch active.',
    'subscription.addon_additional_active_n': 'Currently you have {count} additional branches active.',
    'subscription.addon_total_capacity_0': 'You have no additional branches on your subscription; your plan includes access to {total} branches in total.',
    'subscription.addon_total_capacity_1': 'You currently have 1 additional branch, giving you access to {total} branches in total.',
    'subscription.addon_total_capacity_n': 'You currently have {additional} additional branches, giving you access to {total} branches in total.',
    'subscription.addon_breakdown_title': 'Monthly cost breakdown',
    'subscription.addon_monthly_summary_title': 'Monthly summary',
    'subscription.addon_breakdown_business_plan': 'Base plan',
    'subscription.addon_breakdown_additional': 'Additional branches',
    'subscription.addon_breakdown_estimated_total': 'Total monthly',
    'subscription.addon_price_per': 'MXN/month per additional branch.',
    'subscription.addon_current': 'Current:',
    'subscription.update_addons': 'Update additional branches',
    'subscription.manage': 'Cancel subscription',
    'subscription.upgrade_plan': 'Upgrade plan',
    'subscription.cta_upgrade_to_business': 'Upgrade to Business',
    'subscription.pro_upgrade_title': 'Grow with Business',
    'subscription.pro_upgrade_body':
      'Business is designed for restaurants that need multiple branches and more room to scale.',
    'subscription.pro_upgrade_bullet_0': '3 branches included',
    'subscription.pro_upgrade_bullet_1': 'Unlimited wines',
    'subscription.pro_upgrade_bullet_2': 'Additional branches available',
    'subscription.pro_upgrade_bullet_3': 'Ideal for multi-location operations',
    'subscription.pro_upgrade_bullet_2_ios':
      'Billing and plan changes: App Store settings / Apple Account (we do not use the Stripe web portal on iOS).',
    'subscription.pro_upgrade_bullet_3_ios':
      'Business in this app includes 3 branches; extra branches only with a web subscription (Stripe) on Android or desktop.',
    'subscription.pro_compare_title': 'Compare plans',
    'subscription.pro_compare_pro_label': 'PRO',
    'subscription.pro_compare_business_label': 'BUSINESS',
    'subscription.pro_compare_pro_line_0': '1 branch',
    'subscription.pro_compare_pro_line_1': 'Up to 100 wines',
    'subscription.pro_compare_business_line_0': '3 branches included',
    'subscription.pro_compare_business_line_1': 'Unlimited wines',
    'subscription.pro_compare_business_line_2': 'Additional branches available',
    'subscription.pro_compare_business_line_2_ios':
      'Extra branches only with Stripe (web/Android). On iOS, manage your Apple subscription in the App Store.',
    'subscription.cancel': 'Cancel subscription',
    'subscription.plan_current': 'Current plan',
    'subscription.includes': 'Includes:',
    'subscription.not_includes': 'Not included:',
    'subscription.subscribe_cta': 'Subscribe',
    'subscription.plan_name.cafe': 'Cafe',
    'subscription.plan_name.bistro': 'Bistro',
    'subscription.plan_name.trattoria': 'Trattoria',
    'subscription.plan_name.grand_maison': 'Grand Maison',
    'subscription.period_month': 'month',
    'subscription.price_free': 'Free',
    'subscription.error_no_session': 'No active session',
    'subscription.confirm_subscribe': 'Confirm Subscription',
    'subscription.confirm_subscribe_message': 'Do you want to subscribe to the "{plan}" plan for',
    'subscription.cta_subscribe': 'Subscribe',
    'subscription.no_subscription': 'No Subscription',
    'subscription.no_subscription_message': "You don't have an active subscription. Please subscribe to a plan first.",
    'subscription.error_generic': 'Something went wrong. Please try again.',
    'subscription.alert_ok': 'OK',
    'subscription.alert_open_portal': 'Open portal',
    'subscription.alert_no': 'No',
    'subscription.cancel_confirm_title': 'Cancel subscription',
    'subscription.cancel_confirm_message': 'Cancellation is managed in the Stripe portal. You can cancel or change your plan there. Open portal?',
    'subscription.select_plan_first': 'Please select a plan',
    'subscription.plan_free_title': 'Free Plan',
    'subscription.plan_free_already': 'You are already on the free plan',
    'subscription.plan_invalid_checkout': 'Invalid plan for checkout',
    'subscription.already_subscribed_title': 'You already have a subscription',
    'subscription.already_subscribed_message':
      'For other plan or billing changes, use Cancel subscription on this screen and follow the steps.',
    'subscription.already_subscribed_message_ios':
      'To change or cancel, use Manage subscription. If you paid with Apple, App Store management opens (not the Stripe portal).',
    'subscription.addon_confirm_title': 'Confirm additional branches',
    'subscription.addon_confirm_body': 'You will update your additional branches to',
    'subscription.addon_confirm_cost_per_branch': 'Cost per additional branch',
    'subscription.addon_confirm_extra_monthly': 'Estimated additional monthly charge',
    'subscription.addon_confirm_next_invoice': 'This change will appear on your next invoice (Stripe).',
    'subscription.addon_confirm_no_proration': 'No proration will be applied today (proration_behavior=none).',
    'subscription.addon_confirm_remove_note': 'Additional branches on your subscription will be removed. Your plan-included branches stay the same. Extra branches will be locked until you adjust.',
    'subscription.confirm': 'Confirm',
    'subscription.update_failed_message': 'Could not update. Please try again.',
    'subscription.confirm_update_addons_title': 'Confirm Update',
    'subscription.confirm_update_addons_message': 'Update additional branches to',
    'subscription.update_success_title': 'Update Successful',
    'subscription.update_success_message': 'Additional branches updated to',
    'subscription.profile_loading_retry': 'Could not load profile. Retrying…',
    'subscription.retry': 'Retry',
    'subscription.loading_subscribe': 'Processing subscription…',
    'subscription.loading_portal': 'Opening portal…',
    'subscription.loading_save_additional_branches': 'Saving additional branches…',
    'subscription.apple_manage_title': 'Manage subscription (App Store)',
    'subscription.apple_manage_message':
      'Subscriptions purchased through Apple are managed in Settings > Apple ID > Subscriptions, or from your Apple Account page. We do not open the Stripe web portal for Apple billing.',
    'subscription.apple_manage_open': 'Open Apple account',
    'subscription.apple_restore': 'Restore purchases',
    'subscription.apple_loading_purchase': 'Processing App Store purchase…',
    'subscription.apple_loading_restore': 'Restoring purchases…',
    'subscription.apple_loading_sync': 'Syncing subscription…',
    'subscription.apple_sync_lapsed_title': 'Subscription not active',
    'subscription.apple_sync_lapsed_message':
      'Your receipt shows the subscription is no longer active. Your Cellarium plan was updated.',
    'subscription.apple_success_title': 'Done',
    'subscription.apple_success_message': 'Your plan was synced successfully.',
    'subscription.apple_confirm_title': 'Subscribe with Apple?',
    'subscription.apple_confirm_message':
      'The Apple payment flow will open. The final price is for your App Store region.',
    'subscription.apple_backend_retry_hint':
      'If this was a temporary network or server issue, retry. The transaction is not finished on the device until the server confirms.',
    'subscription.apple_sync_unclear_message':
      'We did not get a clear confirmation from the server. The transaction was not finished on the device; retry with a stable connection.',
    'subscription.apple_restore_ios_hint':
      'Subscriptions purchased through Apple are managed in Settings > Apple ID > Subscriptions.',
    'subscription.branch_reduction_blocked':
      'You cannot reduce additional branches because you currently have more active branches than allowed.',
    'subscription.verify_email_to_update_branches':
      'Verify your email to update additional branches on your subscription.',
    'subscription.verify_email_to_continue': 'Verify your email to continue.',
    'subscription.addons_stripe_only':
      'Variable-quantity additional branches only apply with Stripe billing (web/Android).',
    'subscription.addon_breakdown_base_plan': 'Base plan (see portal / invoice)',
    'subscription.ios_branch_addon_intro':
      'Apple add-on packs (1 or 3 additional branches). After purchase we sync with the server.',
    'subscription.ios_branch_addon_1': '+1 additional branch (Apple)',
    'subscription.ios_branch_addon_3': '+3 additional branches (Apple)',
    'subscription.qty_validation': 'Quantity must be a number between 0 and 50',
    'subscription.plan_updated_title': 'Plan updated',
    'subscription.plan_updated_message': 'Your changes are now active on your account.',
    'subscription.upgrade_success_title': 'Plan updated',
    'subscription.upgrade_success_message':
      'Your subscription was updated successfully. Your new plan is now active.',
    'subscription.upgrade_done_cta': 'Got it',
    'subscription.upgrade_receipt_optional': 'View payment receipt',
    'subscription.addon_saved_modal_title': 'Branches updated',
    'subscription.addon_saved_modal_body':
      'You now have {qty} additional branch(es). Changes apply on your next billing cycle.',
    'subscription.cta_update': 'Update',
    'common.na': 'N/A',
    // Plan features (free)
    'subscription.plan.cafe.features.0': '1 base branch',
    'subscription.plan.cafe.features.1': 'Up to 10 wines and 10 cocktails',
    'subscription.plan.cafe.features.2': '1 additional staff member',
    'subscription.plan.cafe.features.3': 'QR and basic management',
    'subscription.plan.cafe.blocked.0': 'Inventory & analytics',
    'subscription.plan.cafe.blocked.1': 'Tastings',
    'subscription.plan.bistro.features.0': '50 wines',
    'subscription.plan.bistro.features.1': '50 cocktails',
    'subscription.plan.bistro.features.2': 'Up to 3 staff members',
    'subscription.plan.bistro.features.3': 'Premium features unlocked',
    'subscription.plan.trattoria.features.0': '150 wines',
    'subscription.plan.trattoria.features.1': '75 cocktails',
    'subscription.plan.trattoria.features.2': 'Unlimited staff',
    'subscription.plan.grand_maison.features.0': 'Unlimited wines',
    'subscription.plan.grand_maison.features.1': 'Unlimited cocktails',
    'subscription.simulate_title': 'Simulate Payment (DEV ONLY)',
    'subscription.simulate_message': 'Simulate successful payment for',
    'subscription.simulate_cta': 'Simulate',
    'subscription.simulate_success': 'Simulation Successful',
    'subscription.simulate_success_message': 'activated (simulated).',

    'admin.cocktail_menu': 'Cocktail Menu',
    'admin.cocktail_menu_sub': 'Manage exclusive branch drinks',
    
    // Cocktail Menu
    'cocktail.title': 'Cocktail Menu',
    'cocktail.subtitle': 'Manage exclusive drinks for this branch',
    'cocktail.add_drink': 'Add Drink',
    'cocktail.edit_drink': 'Edit Drink',
    'cocktail.delete_drink': 'Delete Drink',
    'cocktail.name': 'Drink Name',
    'cocktail.name_es': 'Name (Spanish)',
    'cocktail.name_en': 'Name (English)',
    'cocktail.description': 'Description',
    'cocktail.description_es': 'Description (Spanish)',
    'cocktail.description_en': 'Description (English)',
    'cocktail.ingredients': 'Ingredients',
    'cocktail.ingredients_es': 'Ingredients (Spanish)',
    'cocktail.ingredients_en': 'Ingredients (English)',
    'cocktail.ingredient_placeholder': 'E.g: Rum, Lemon, Sugar...',
    'cocktail.price': 'Price',
    'cocktail.price_placeholder': '0.00',
    'cocktail.photo': 'Drink Photo',
    'cocktail.choose_aspect': 'Crop format',
    'cocktail.aspect_3_4': 'Rectangular (3:4)',
    'cocktail.aspect_1_1': 'Square (1:1)',
    'cocktail.take_photo': 'Take Photo',
    'cocktail.select_from_gallery': 'Select from Gallery',
    'cocktail.gallery_line1': 'Select from',
    'cocktail.gallery_line2': 'Gallery',
    'cocktail.save': 'Save Drink',
    'cocktail.cancel': 'Cancel',
    'cocktail.delete_confirm': 'Are you sure you want to delete this drink?',
    'cocktail.delete_success': 'Drink deleted successfully',
    'cocktail.save_success': 'Drink saved successfully',
    'cocktail.save_error': 'Error saving drink',
    'cocktail.limit_free_10': 'Free plan limit: maximum 10 active cocktails per branch. Verify your email or upgrade to Pro/Business for unlimited.',
    'cocktail.delete_error': 'Error deleting drink',
    'cocktail.name_required': 'Name is required',
    'cocktail.ingredients_required': 'Ingredients are required',
    'cocktail.price_required': 'Price is required',
    'cocktail.price_invalid': 'Price must be a valid number',
    'cocktail.no_drinks': 'No drinks in menu',
    'cocktail.add_first': 'Add your first drink',
    'cocktail.beverages_available': 'drinks available',
    'cocktail.empty_primary': 'No drinks yet',
    'cocktail.empty_secondary': 'Add your first exclusive creation',
    'cocktail.loading': 'Loading menu...',
    'cocktail.uploading_image': 'Uploading image...',
    'cocktail.permission_required': 'Permission required',
    'cocktail.camera_access': 'We need camera access',
    'cocktail.gallery_access': 'We need gallery access',
    'cocktail.error_capture': 'Error capturing image',
    'cocktail.error_select': 'Error selecting image',
    'cocktail.error_upload': 'Error uploading image',
    'cocktail.error_compress': 'Error compressing image',
    'cocktail.compressing_image': 'Compressing image...',
    
    // Wine Management
    'wine_mgmt.title': 'Manual wine entry',
    'wine_mgmt.hero_description': 'Add a front photo and fill in the basic details.',
    'wine_mgmt.photo_hint': 'Clear and glare-free.',
    'wine_mgmt.front_label': 'Front Label (required)',
    'wine_mgmt.back_label': 'Back Label (optional)',
    'wine_mgmt.additional_photos': 'Additional Photos (optional)',
    'wine_mgmt.pro_camera': 'Pro Camera',
    'wine_mgmt.gallery': 'Gallery',
    'wine_mgmt.process_ai': 'Process with AI',
    'wine_mgmt.processing': 'Saving...',
    'wine_mgmt.processing_label': 'Saving...',
    'wine_mgmt.front_label_camera': 'Front Label',
    'wine_mgmt.back_label_camera': 'Back Label',
    'wine_mgmt.camera_auto_capture': 'The camera will automatically detect the label and capture when stable',
    'wine_mgmt.close': 'Close',
    'wine_mgmt.save_wine': 'Save wine',
    'wine_mgmt.permission_required': 'Permission Required',
    'wine_mgmt.gallery_access': 'We need access to the gallery',
    'wine_mgmt.camera_access': 'We need access to the camera to capture the label',
    'wine_mgmt.error_select_front': 'Could not select front image',
    'wine_mgmt.error_select_back': 'Could not select back image',
    'wine_mgmt.error_capture_front': 'Could not capture front image',
    'wine_mgmt.error_capture_back': 'Could not capture back image',
    'wine_mgmt.error_select_additional': 'Could not select additional image',
    'wine_mgmt.error_no_front': 'You must capture at least the front label photo',
    'wine_mgmt.error_process_labels': 'Could not process labels. Please try again.',
    'wine_mgmt.error_capture': 'Could not capture image',
    'wine_mgmt.error_process': 'Could not process label. Please try again.',
    'wine_mgmt.error_camera': 'Camera Error',
    'wine_mgmt.missing_fields': 'Missing Required Fields',
    'wine_mgmt.missing_fields_msg': 'Please complete the following fields before adding the wine to the catalog:',
    'wine_mgmt.understood': 'Understood',
    'wine_mgmt.error_stock': 'Please enter initial stock',
    'wine_mgmt.error_branch': 'No branch selected',
    'wine_mgmt.error_auth': 'User not authenticated',
    'wine_mgmt.success_title': '✅ Wine Registered',
    'wine_mgmt.success_msg': 'has been added to the catalog with',
    'wine_mgmt.success_bottles': 'bottles in stock.',
    'wine_mgmt.add_another': 'Add Another',
    'wine_mgmt.view_catalog': 'View Catalog',
    'wine_mgmt.error_save': 'Could not save wine:',
    'wine_mgmt.bottle_image': '🖼️ Bottle Image',
    'wine_mgmt.select_image': 'Select a suggested image or upload your own photo',
    'wine_mgmt.suggested_images': 'AI Suggested Images',
    'wine_mgmt.upload_own': '📤 Upload My Own Image',
    'wine_mgmt.continue': 'Continue',
    'wine_mgmt.alcohol_content': 'Alcohol Content',
    'wine_mgmt.description': 'Description',
    'wine_mgmt.wine_type': 'Wine type',
    'wine_mgmt.name': 'Wine name',
    'wine_mgmt.winery': 'Winery',
    'wine_mgmt.grape_variety': 'Grape variety',
    'wine_mgmt.vintage': 'Vintage',
    'wine_mgmt.region': 'Region',
    'wine_mgmt.country': 'Country',
    'wine_mgmt.section_wine_info': 'Wine Information',
    'wine_mgmt.section_prices': 'Prices and Stock',
    'wine_mgmt.price_glass': 'Price per Glass',
    'wine_mgmt.price_bottle': 'Price per Bottle',
    'wine_mgmt.price_bottle_optional': 'Bottle price (optional)',
    'wine_mgmt.initial_stock': 'Initial Stock',
    'wine_mgmt.select_image_btn': 'Select image',
    'wine_mgmt.change_image': 'Change image',
    'wine_mgmt.tasting_notes': 'Tasting notes',
    'wine_mgmt.pairings': 'Pairings',
    'wine_mgmt.serving_temp': 'Serving temperature',
    'wine_mgmt.alcohol_pct': '% Alcohol',
    'wine_mgmt.stock_help': 'Bottles in stock. Later changes are made from Inventory Control.',
    'wine_mgmt.placeholder_name': 'e.g. Château Margaux',
    'wine_mgmt.placeholder_grape': 'e.g. Cabernet Sauvignon',
    'wine_mgmt.placeholder_region': 'e.g. Bordeaux',
    'wine_mgmt.placeholder_country': 'e.g. France',
    'wine_mgmt.placeholder_pairings': 'Red meats, cheeses, etc.',
    'wine_mgmt.placeholder_temp': '16-18°C',
    'wine_mgmt.placeholder_desc': 'General wine description...',
    'wine_mgmt.placeholder_tasting': 'Aromas, flavors, texture...',
    'wine_mgmt.section_sensory': 'Sensory profile',
    'wine_mgmt.sensory_help': 'Optional. Values 1–5 shown on the wine card (Body, Sweetness, Acidity, Tannin).',
    
    // Global Wine Catalog
    'global_catalog.title': 'Cellarium Catalog',
    'global_catalog.subtitle': 'wines available • Page',
    'global_catalog.of': 'of',
    'global_catalog.search': 'Search',
    'global_catalog.search_placeholder': 'Search wine...',
    'global_catalog.all_wines': 'All Wines',
    'global_catalog.red': 'Red',
    'global_catalog.white': 'White',
    'global_catalog.rose': 'Rosé',
    'global_catalog.sparkling': 'Sparkling',
    'global_catalog.dessert': 'Dessert Wines',
    'global_catalog.fortified': 'Fortified',
    'global_catalog.view_details': 'View Details',
    'global_catalog.add': 'Add',
    'global_catalog.already_added': 'Wine Already Added',
    'global_catalog.loading': 'Loading catalog...',
    'global_catalog.no_wines': 'No wines found',
    'global_catalog.no_image': 'No image',
    'global_catalog.vintage': 'Vintage:',
    'global_catalog.loading_details': 'Loading details...',
    'global_catalog.country': 'Country:',
    'global_catalog.region': 'Region:',
    'global_catalog.color': 'Color:',
    'global_catalog.varietals': 'Varietals',
    'global_catalog.alcohol': 'Alcohol:',
    'global_catalog.volume': 'Volume:',
    'global_catalog.closure': 'Closure:',
    'global_catalog.style': 'Style:',
    'global_catalog.appellation': 'Appellation:',
    'global_catalog.flavors': 'Flavors',
    'global_catalog.tasting_profile': 'Tasting Profile',
    'global_catalog.pairings': 'Pairings',
    'global_catalog.vinification': 'Vinification',
    'global_catalog.close': 'Close',
    'global_catalog.add_to_catalog': 'Add to Catalog',
    'global_catalog.restaurant_name_required': 'Restaurant Name Required',
    'global_catalog.restaurant_name_owner_msg': 'Before adding wines, you must define your restaurant or consumption center name. You can edit it from Branch Management.',
    'global_catalog.restaurant_name_staff_msg': 'The owner must define the restaurant or consumption center name before adding wines. Contact the responsible person to configure it.',
    'global_catalog.later': 'Later',
    'global_catalog.go_to_management': 'Go to Management',
    'global_catalog.understood': 'Understood',
    'global_catalog.error_load': 'Error loading wines',
    'global_catalog.error_unknown': 'Unknown error',
    'global_catalog.error_details': 'Could not load wine details',
    'global_catalog.error_load_details': 'Error loading details',
    'global_catalog.body': 'Body',
    'global_catalog.acidity': 'Acidity',
    'global_catalog.fizziness': 'Fizziness',
    'global_catalog.tannin': 'Tannin',
    'global_catalog.sweetness': 'Sweetness',
  },
};

const LANGUAGE_STORAGE_KEY = '@cellarium_language';

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('es');

  // Cargar idioma guardado al iniciar
  useEffect(() => {
    loadSavedLanguage();
  }, []);

  const loadSavedLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (savedLanguage === 'es' || savedLanguage === 'en') {
        setLanguageState(savedLanguage as Language);
      }
    } catch (error) {
      console.error('Error loading saved language:', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      setLanguageState(lang);
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  // Función de traducción
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // Función para obtener valores bilingües
  const getBilingualValue = (
    value: string | { en?: string; es?: string } | null | undefined,
    fallback: string = ''
  ): string => {
    if (!value) return fallback;
    
    if (typeof value === 'string') {
      return value;
    }
    
    if (typeof value === 'object' && value !== null) {
      const langValue = value[language];
      if (langValue && typeof langValue === 'string') return langValue;
      
      // Fallback al otro idioma si no existe en el idioma actual
      const fallbackLang = language === 'es' ? 'en' : 'es';
      const fallbackValue = value[fallbackLang];
      if (fallbackValue && typeof fallbackValue === 'string') return fallbackValue;
    }
    
    return fallback;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
    getBilingualValue,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
